name: Release Calendar GitHub Action
description: This is a github actions to check whether release allowed or not based on release calendar

author: Saurabh Jambhule

branding:
  color: green
  icon: calendar

inputs:
  timezone:
    description: Calendar timezone
    default: "Asia/Kolkata"
    required: true

outputs:
  release_freeze:
    description: Whether release allowed or not

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.timezone }}
