name: Build and Test GitHub Action

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - reopened

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run the private action
        id: release
        uses: ./
        with:
          timezone: 'Asia/Kolkata'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
          STATUS_CONTEXT: 'Production Deploy Approved'

      - name: Get the output
        shell: bash
        run: |
          echo ${{ steps.release.outputs.release_freeze }}
